name: Deploy Digimon App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir la imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/digimon-app .

      - name: Subir la imagen a Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/digimon-app